### PR TITLE
Path splitting uses conventional node methods

### PR DESCRIPTION
**Pull request by SgtPooki**
Fixes unstoppablecarl/metalsmith-navigation#5

### CODE REVIEW

**Comment by unstoppablecarl** [comment]
I think it should still use `path.sep`. What do you think?

```js
var replaceDirsSeparator = function(navFiles) {
    var regExp = new RegExp('/' + path.sep + '/', 'g');
    var newKey;
    var oldKey;

    // Path is used as key in navFiles, some paths have \\ as separator between folders
    for (oldKey in navFiles) {
        // Replace \\ separator by /
        newKey = oldKey.replace(regExp, '/');

        if (oldKey !== newKey) {
            navFiles[newKey] = navFiles[oldKey];
            delete navFiles[oldKey];
        }
    }
    return navFiles;
};

```

**Comment by unstoppablecarl** [comment]
@SgtPooki ?

**Comment by SgtPooki** [comment]
hey @unstoppablecarl , sorry for the delay. I chose to go with the regex expression instead of the ```new RegExp``` method because it is quicker. Also, if we used path.sep, it's going to end up replacing '/' with '/' wasting even more cpu cycles.

**Comment by SgtPooki** [comment]
Granted, not by much.. but.. http://jsfiddle.net/SgtPooki/zvqgorrv/

```
path1, regex1 - matches found x 1,803,955 ops/sec ±4.60% (84 runs sampled)
path2, regex1 - no matches found(none needed) x 7,134,691 ops/sec ±3.13% (89 runs sampled)
```
If we ran the replace using path.sep, we would be using the following for path2 (non-windows users):
```
path2, newReg2 - matches found(none needed) x 1,877,061 ops/sec ±2.75% (88 runs sampled)
//or 
path2, regex2 - matches found(none needed) x 1,798,905 ops/sec ±3.99% (81 runs sampled)
```

**Comment by unstoppablecarl** [comment]
I think this is a good example of premature optimization. The `path.sep` is more flexible and reads easier I think.

**Comment by SgtPooki** [comment]
I think a 700% speed increase for 60%+ of your user base is far from a premature optimization. No offense, but I personally think trying to excuse lack of efficiency with the term "premature optimization" or "over optimization" is proof of tunnel vision. If this plugin becomes heavily used in the future, this is a huge bottleneck.

Also, the code is already there. Reverting it, or even discussing it at this point, is more wasteful than any sort of premature optimization this may fall into.

**Pull request merged**
