### PR TITLE
Sort by first child if it's a directory.

### PR DESCRIPTION
**Pull request by oblador**
I'm using the permalinks plugin which makes every post sit in their own folder effectively making them get sorted in arrays of one. With this patch the plugin with look ahead to it's first child (if it exists) to get a value to sort by if it's a directory.

### CODE REVIEW

**Comment by unstoppablecarl** [comment]
Can you provide an example of what the order would look like before and after your PR changes are merged? I con't completely get what this is doing.

**Comment by oblador** [comment]
My current setup: 
```
var navConfigs = {
  primary:{
    sortBy: 'sort',
    sortByNameFirst: false,
    filterProperty: 'in_nav',
    includeDirs: true
  }
};

var navSettings = {
  navListProperty: 'navs',
  permalinks: true
};
```

This results in no sorting at all since permalinks plugin will create this structure: 
```
collection/page1/index.html
collection/page2/index.html
```

**Comment by unstoppablecarl** [comment]
are you running the permalinks plugin before or after the navigation plugin?

**Comment by oblador** [comment]
Before.

**Comment by unstoppablecarl** [comment]
I am not comfortable with the side effects this will introduce. I think any transformation should be done in the transformPermalinks function.

**Comment by unstoppablecarl** [comment]
Although that comes after the sorting. If you email me we can chat and figure this out.

**Comment by oblador** [comment]
Uh, no transformation is made. This is strictly a fix for your sorter algorithm. Merge or not.

**Comment by unstoppablecarl** [comment]
@oblador can you please email me so we can chat on google hangouts or skype? I would very much like to figure out the best solution to this problem.

**Comment by unstoppablecarl** [comment]
Fixed by latest update

**Pull request closed without merging**
