### PR TITLE
Fix issue #14 -- allow permalink submenus to sort by front matter

### PR DESCRIPTION
**Pull request by jmjf**
See [https://github.com/jmjf/ms-nav-issue14](https://github.com/jmjf/ms-nav-issue14) for detailed discussion and test case.

### CODE REVIEW

**Comment by unstoppablecarl** [comment]
@jmjf look at the `mergeMatchingFilesAndDirs` and `includeDirs` nav config settings.

**Comment by unstoppablecarl** [comment]
When considering the values of `mergeMatchingFilesAndDirs` and `includeDirs` when building with non-permalinks, is there still unexpected behavior?

**Comment by jmjf** [comment]
Given the sort order set in the source files, here's what I'd expect to see as a sort order.
subitem(.html), test(.html), index.html, about(.html).

Here's the order I get with various settings.

**includeDirs = true and mergeMatchingFilesAndDirs = true (what I was running with originally)**
NoPerma -> subitem.html, test.html (subitem child), index.html, about.html
Perma -> index.html, about, subitem, test (subitem child)

**includeDirs = true and mergeMatchingFilesAndDirs = false**
NoPerma -> subitem.html, index.html, about.html, subitem, test.html (subitem child)
Perma -> index.html, about, subitem, test (subitem.child) 
(note, index.html is merged onto permalink directories for about, subitem, and test--i.e., about's file.nav_path = about/index.html)

**includeDirs = false and mergeMatchingFilesAndDirs = true**
NoPerma -> subitem.html, test.html (subitem child), index.html, about.html
Perma -> index.html

**includeDirs = false and mergeMatchingFilesAndDirs = false**
NoPerma -> subitem.html, index.html, about.html
Perma -> index.html

Based on these results, the true/true case sorts correctly for no-perma, but no-perma does not indicate that subitem is a menu parent. Arguably, I could deduce that from the fact it has children.

But I'm running with permalinks, and no case sorts correctly for perma. If change metalsmith-navigation to permalinks = false (which is counterintuitive given the documentation), I get:

index.html, about, index.html (about child), subitem, index.html (subitem child), test (subitem child), index.html (test child)

which still isn't the right order. When using permalinks and submenus, I'm not sure how I'd sort submenus without hardcoding, which defeats the purpose of the plugin.

I think the issue is, permalinks only match dirs to child files if there is only one child (see code below).

```js
    if(usePermalinks){
        var _sortBy = sortBy;
        sortBy = function(node){

            // if node is dir and has 1 child sort using that child node instead of the dir
            if(!node.file && node.children.length === 1){
                node = node.children[0];
            }
            return _sortBy(node);
        };
    }
```

In the case of a submenu with child items in a subdirectory, there will be >1 child, so the code above will not match any child files to the parent and the parent cannot be sorted. This is what I changed in this pull request.

Hope that helps see what I'm trying to do and why I think a code change is needed. If I'm missing something obvious, let me know and I'll try it out.

**Comment by unstoppablecarl** [comment]
It makes sense my concern is: Does your PR break the current behavior for non-permalinks?

**Comment by jmjf** [comment]
Ah, I see your question. My guess is not, because it's all inside the `if(permalinks)` block, but let me run it. I have metalsmith-navigation and metalsmith-navigation-mod in node_modules so I can switch between the two versions easily. Results below are noperma before and after, following the pattern above.

**includeDirs = true and mergeMatchingFilesAndDirs = true**
Before-> subitem.html, test.html (subitem child), index.html, about.html
After -> subitem.html, test.html (subitem child), index.html, about.html

**includeDirs = true and mergeMatchingFilesAndDirs = false**
Before -> subitem.html, index.html, about.html, subitem, test.html (subitem child)
After -> subitem.html, index.html, about.html, subitem, test.html (subitem child)

**includeDirs = false and mergeMatchingFilesAndDirs = true**
Before -> subitem.html, test.html (subitem child), index.html, about.html
After -> subitem.html, test.html (subitem child), index.html, about.html

**includeDirs = false and mergeMatchingFilesAndDirs = false**
Before -> subitem.html, index.html, about.html
After -> subitem.html, index.html, about.html

All matches, so this only affects permalinks:true. And, for the sake of completeness, here's before and after for permalinks:true.

**includeDirs = true and mergeMatchingFilesAndDirs = true**
Before -> index.html, about, subitem, test (subitem child)
After -> subitem, test (subitem child), index.html, about
(Files are linked to directories so subitem has file.nav_path = subitem/index.html, etc.)

**includeDirs = true and mergeMatchingFilesAndDirs = false**
Before -> index.html, about, subitem, test (subitem.child)
After -> subitem, test (subitem child), index.html, about
(Files linked to directories because these are permalinks--same as unmodified code.)

**includeDirs = false and mergeMatchingFilesAndDirs = true**
Before -> index.html
After -> index.html

**includeDirs = false and mergeMatchingFilesAndDirs = false**
Before -> index.html
After -> index.html

So, for permalinks, mergeMatchingFilesAndDirs doesn't do much, but that seems reasonable, given how permalinks work, and is consistent with the unmodified code. The menu will never include more than one item for includeDirs = false, which is consistent with the unmodified code. Given how permalinks work, if someone is using permalinks and wants to set includeDirs = false, they don't need this plugin.

**Pull request merged**
